version: "3.8"

services:
  gateway-db:
    container_name: gateway_db
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=gateway
      - MYSQL_USER=musala
      - MYSQL_PASSWORD=musala
    volumes:
      - gateway-db-volume:/var/lib/mysql
    networks:
      - gateway-network

  backend-app:
    container_name: backend_app
    depends_on:
      - gateway-db
    build: ./gateway
    restart: always
    ports:
      - 8080:8080
    environment: 
      - MYSQL_HOST=gateway-db
      - MYSQL_PORT=3306
      - MYSQL_USERNAME=musala
      - MYSQL_PASSWORD=musala
    networks:
      - gateway-network

networks:
  gateway-network:

volumes:
  gateway-db-volume: